import React from 'react';
import {FaLinkedinIn,FaTwitter,FaFacebookF,FaInstagram,FaBookmark} from 'react-icons/fa';
import {FaEye} from 'react-icons/fa';

export const Data =[
    {
        id:1,
        image:'https://cdn.mindmajix.com/authors/viswanath-160920.jpg',
        Name:'Viswanath V S',
        designation:'Content Writer',
        topic:'Data Science, Artificial Intelligence, Machine Learning, Blockchain, etc',
        text:'Viswanath is a passionate content writer of Mindmajix. He has expertise in Trending Domains. His articles help the learners to get insights about the Domain. You can reach him on Linkedin.',
        icon1:'https://www.linkedin.com/in/sowmithri-viswanath-2b714095/',
        // icon2:,
        icon3:'a',
        icon4:'b'  ,
    },
]

export const article=[
    {
        id:2,
        photo:'https://blog.hubspot.com/hubfs/woman%20reposting%20on%20instagram.jpg',
        articletext:'How to Repost on Instagram: 4 Ways to Reshare Content From Other Users',
        rating:'Rating:',
        points:'4.6',
        eye:<FaEye/>,
        number:'24',
        
    },
    {
        id:3,
        photo:'https://blog.hubspot.com/hubfs/Copy%20of%20Untitled-Dec-21-2021-11-53-05-44-PM.png',
        articletext:'How to Use Facebook Live: The Ultimate Guide',
        rating:'Rating:',
        points:'4.6',
        star:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSILhLaWmXzwL84QqABr1JbTdmTphJ-9EemXAPbm_KOgDqUN5y5',
        eye:<FaEye/>,
        number:'24',    },
    {
        id:4,
        photo:'https://blog.hubspot.com/hubfs/social-media-content-calendar-tools-1.jpg',
        articletext:'13 Social Media Calendars, Tools, & Templates to Plan Your Content',
        rating:'Rating:',
        points:'4.6',
        star:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSILhLaWmXzwL84QqABr1JbTdmTphJ-9EemXAPbm_KOgDqUN5y5',
        eye:<FaEye/>,
        number:'24',
    },
    {
        id:5,
        photo:'https://blog.hubspot.com/hubfs/online-marketing-courses.jpg',
        articletext:'50 Free Online Marketing Classes to Take This Year',
        rating:'Rating:',
        points:'4.6',
        star:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSILhLaWmXzwL84QqABr1JbTdmTphJ-9EemXAPbm_KOgDqUN5y5',
        eye:<FaEye/>,
        number:'24',
    },
    {
        id:6,
        photo:'https://blog.hubspot.com/hubfs/how-to-make-an-instagram-story.jpg',
        articletext:'Instagram Stories: What They Are and How to Make One Like a Pro',
        rating:'Rating:',
        points:'4.6',
        star:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSILhLaWmXzwL84QqABr1JbTdmTphJ-9EemXAPbm_KOgDqUN5y5',
        eye:<FaEye/>,
        number:'24',
    },
    {
        id:7,
        photo:'https://blog.hubspot.com/hubfs/scarcity-principle.jpg',
        articletext:'The Scarcity Principle: How 7 Brands Created High Demand [Research]',
        rating:'Rating:',
        points:'4.6',
        star:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSILhLaWmXzwL84QqABr1JbTdmTphJ-9EemXAPbm_KOgDqUN5y5',
        eye:<FaEye/>,
        number:'24',
    },
    {
        id:8,
        photo:'https://blog.hubspot.com/hubfs/content-marketing-templates-1.jpg',
        articletext:'The Ultimate Collection of Free Content Marketing Templates',
        rating:'Rating:',
        points:'4.6',
        star:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSILhLaWmXzwL84QqABr1JbTdmTphJ-9EemXAPbm_KOgDqUN5y5',
        eye:<FaEye/>,
        number:'24',
    },
    {
        id:9,
        photo:'https://blog.hubspot.com/hubfs/instagram-quote-maker.jpg',
        articletext:'How to Make Quotes for Instagram: 11 Apps to Try This Year',
        rating:'Rating:',
        points:'4.6',
        star:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSILhLaWmXzwL84QqABr1JbTdmTphJ-9EemXAPbm_KOgDqUN5y5',
        eye:<FaEye/>,
        number:'24',
    },
    {
        id:10,
        photo:'https://blog.hubspot.com/hubfs/diy-office-costume-ideas.jpg',
        articletext:'35 Office Costume Ideas for Marketing Nerds & Tech Geeks',
        rating:'Rating:',
        points:'4.6',
        star:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSILhLaWmXzwL84QqABr1JbTdmTphJ-9EemXAPbm_KOgDqUN5y5',
        eye:<FaEye/>,
        number:'24',
    },
    {
        id:11,
        photo:'https://blog.hubspot.com/hubfs/facebook-ad-examples-1.jpg',
        articletext:'13 Examples of Facebook Ads That Actually Work (And Why)',
        rating:'Rating:',
        points:'4.6',
        star:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSILhLaWmXzwL84QqABr1JbTdmTphJ-9EemXAPbm_KOgDqUN5y5',
        eye:<FaEye/>,
        number:'24',
    },
    {
        id:12,
        photo:'https://blog.hubspot.com/hubfs/how-to-write-a-video-scipt.jpg',
        articletext:'How to Write a Video Script [Template + Video]',
        rating:'Rating:',
        points:'4.6',
        star:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSILhLaWmXzwL84QqABr1JbTdmTphJ-9EemXAPbm_KOgDqUN5y5',
        eye:<FaEye/>,
        number:'24',
    },
    {
        id:13,
        photo:'https://blog.hubspot.com/hubfs/co-branding-partnership-business-examples.jpg',
        articletext:'21 Examples of Successful Co-Branding Partnerships (And Why They are So Effective)',
        rating:'Rating:',
        points:'4.6',
        star:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSILhLaWmXzwL84QqABr1JbTdmTphJ-9EemXAPbm_KOgDqUN5y5',
        eye:<FaEye/>,
        number:'24',
    },
    {
        id:14,
        photo:'https://blog.hubspot.com/hubfs/best-chrome-extensions.jpg',
        articletext:'The 70 Best Chrome Extensions for 2022',
        rating:'Rating:',
        points:'4.6',
        star:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSILhLaWmXzwL84QqABr1JbTdmTphJ-9EemXAPbm_KOgDqUN5y5',
        eye:<FaEye/>,
        number:'24',
    },
    {
        id:15,
        photo:'https://blog.hubspot.com/hubfs/best-video-editing-software-1.jpg',
        articletext:'The 20 Best Video Editing Apps for 2022',
        rating:'Rating:',
        points:'4.6',
        star:'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSILhLaWmXzwL84QqABr1JbTdmTphJ-9EemXAPbm_KOgDqUN5y5',
        eye:<FaEye/>,
        number:'24',
    },
    {
        id:16,
        photo:'https://blog.hubspot.com/hubfs/personal-website-1.jpg',
        articletext:'Best Personal Websites: 19 Examples to Blow Your Mind',
        rating:'Rating:',
        points:'4.6',
        star:'<FaStar /><FaStar /><FaStar /><FaStar /><FaStarHalfAlt />',
        eye:<FaEye/>,
        number:'24',
    },

]